# Site settings
title: cv
twitter_username: robi-lion 
name: Robinson Egbo 

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/robi-lion
 - title: StackOverflow
   url: https://stackoverflow.com/users/13630912/robi-lion
 - title: LinkedIn
   url: https://www.linkedin.com/in/robinson-egbo

#Any buzzword skills you want to include
skills:
 - ArcGIS 
 - GPS
 - Microsoft Office Suites 
 - R 
 - Python 
 - Github
 - SQL
 - Field Research
 - Machine learning
 - Data Mining
 
#Work experience is required
roles:
 - title: Cadastral/GIS Analyst 
   start: 2018
   end: Ongoing
   employer: Teqbridge Limited 
   description: I use ESRI software experiences in ArcMap, Python, and Database management to deliver a configurable modular system in the management of land registration, cadastral property assessments, valuation, and revenue collections at the State Secretariat, Alausa-Ikeja, Lagos, Nigeria.
  - title: Urban Planner Northern Division
   start: 2017
   end: 2018
   employer: Federal Capital Development Authority
   description: Performed multiple GIS analysis from incetion to completion using ESRI 10.X software suite. The analysis includes extensive use of ArcTools for data management and analysis functions.
 - title: Administrative Assistant
   start: 2018
   end: 2018
   employer: Yatglow Global Ventures
   description: Preparing, maintaining of documentation activities in the office.

#Education is required
education:
 - level: Bachelor of Science (BSc)
   date: 2016
   subject: Geography
   school: Obafemi Awolowo University

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/91c42d92ee5fafa82bfe5596dce9a415
   courses:
    - title: IBM Professional Data Science Certificate
      link: https://www.coursera.org/specializations/DataSc
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: UC, Davis Geographic Information Systems
      link: https://www.coursera.org/specializations/gis
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014
    - title: JHU Data Science Specialization
      link: https://www.coursera.org/specializations/JHU
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
ESRI MOOC:
      profileurl: https://www.esri.com/user/
      courses:
      - title: Cartography
      - title: The location Advantage
      - title: Spatiial Data Science: The New Frontier in Analytics
      
      

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/robi-lion
  
intro: |
 I am a Geographic Information Systems Analyst committed to efficient database management of Geographic data with minimal error. 
 Garnered years of experiencein Mapping and Planning jobs, extensive knowledge on housing foreclosure, spatial analysis and project experience.
 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   
theme: jekyll-theme-cayman
